apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: default
spec:
  destination:
    namespace: alloy
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values_override.yaml
    path: helm_charts/alloy-1.11.1
    repoURL: https://github.com/santhoshkumarasamy/loki-grafana-00
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true