apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: default
spec:
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: grafana
    helm:
      parameters:
      - name: namespaceOverride
        value: grafana
    repoURL: https://grafana-community.github.io/helm-charts
    targetRevision: 12.11.1
  syncPolicy:
    automated:
      enabled: true
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true